CREATE TABLE Clients(
ClientId INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Phone VARCHAR(12) NOT NULL CHECK(LEN(Phone)=12)
)


CREATE TABLE Mechanics(
MechanicId INT NOT NULL PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
[Address] NVARCHAR(255) NOT NULL
)

CREATE TABLE Jobs(
JobId INT PRIMARY KEY IDENTITY,
ModelId INT NOT NULL FOREIGN KEY REFERENCES Models(ModelId),
[Status] NVARCHAR(11) NOT NULL CHECK([Status] IN ('Pending','In Progress','Finished')) DEFAULT('Pending'),
ClientId INT NOT NULL FOREIGN KEY REFERENCES Clients(ClientId),
MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
IssueDate DATE NOT NULL,
FinishDate DATE
)
CREATE TABLE Models(
ModelId INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Orders(
OrderId INT PRIMARY KEY IDENTITY,
JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
IssueDate DATE,
Delivered BIT NOT NULL DEFAULT 0
)

CREATE TABLE Parts(
PartId INT PRIMARY KEY IDENTITY,
SerialNumber NVARCHAR(50) NOT NULL UNIQUE,
Description NVARCHAR(255),
Price MONEY NOT NULL CHECK(Price>0),
VendorId INT NOT NULL FOREIGN KEY REFERENCES Vendors(VendorId),
StockQty INT NOT NULL CHECK(StockQty>=0) DEFAULT 0
)

CREATE TABLE OrderParts(
OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderId),
PartId INT NOT NULL FOREIGN KEY REFERENCES Parts(PartId),
Quantity INT NOT NULL CHECK(Quantity>0) DEFAULT 1
PRIMARY KEY(OrderId,PartId)
)

CREATE TABLE PartsNeeded(
JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
PartId INT NOT NULL FOREIGN KEY REFERENCES Parts(PartId),
Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1
PRIMARY KEY(JobId,PartId)
)

CREATE TABLE Vendors(
VendorId INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL UNIQUE
)